### ISSUE TITLE
LOGOS

### ISSUE THREAD

**Issue by NickMECS** [pzetairoi/TinyMRP#10]
It would be good to have MECS Logo to left hand corner Index page & visual page
![image](https://github.com/pzetairoi/TinyMRP/assets/167039369/1e0190c8-b546-479e-b59a-4e1af909efa6)
 & MRP Logo middle bottom of all pages

**Comment by pzetairoi** [comment]
done
![image](https://github.com/pzetairoi/TinyMRP/assets/86654415/09711889-cc9f-438f-b6f0-f12e07b57174)
