### ISSUE TITLE
HARDWARE PAGE

### ISSUE THREAD

**Issue by NickMECS** [pzetairoi/TinyMRP#11]
Needs Justifying
![image](https://github.com/pzetairoi/TinyMRP/assets/167039369/2d5a5336-af7b-45d2-a045-b57d30e0d6f5)

**Comment by pzetairoi** [comment]
DOne

![image](https://github.com/pzetairoi/TinyMRP/assets/86654415/649587c9-eefe-4385-99ed-0a6f35414eb9)
