### ISSUE TITLE
USER SPECIFIED NAME CAUSES BOM ERROR

### ISSUE THREAD

**Issue by NickMECS** [pzetairoi/TinyMRP#15]
![image](https://github.com/pzetairoi/TinyMRP/assets/167039369/fd25d16e-e7bc-4967-80b0-3607623c890f)

**Comment by pzetairoi** [comment]
I think the problem are the spaces, please try to replace the spaces with a "-" or "_". I need to put a guide of the partnumbering rules/issues

**Comment by NickMECS** [comment]
YEP THAT MADE IT WORK
