### ISSUE TITLE
MOVE FOR QUOTATION ONLY STAMP

### ISSUE THREAD

**Issue by NickMECS** [pzetairoi/TinyMRP#18]
Can you please move it to bottom left hand corner
![image](https://github.com/pzetairoi/TinyMRP/assets/167039369/0d5eae0f-de08-4da2-ac15-ad05819a5300)

**Comment by pzetairoi** [comment]
Easy one and done

![image](https://github.com/pzetairoi/TinyMRP/assets/86654415/a7a98926-ca4d-4553-9006-b33b653fe263)
