### ISSUE TITLE
EXCEL COMPILE SHEET IN DOWNLOAD RESOURCES

### ISSUE THREAD

**Issue by NickMECS** [pzetairoi/TinyMRP#5]
Works no worries but can you make it blank

![image](https://github.com/pzetairoi/TinyMRP/assets/167039369/1e94ddc0-b344-4bb9-871f-ea0099f514d3)

**Comment by pzetairoi** [comment]
The issues lists works, perfect way to track. Thanks for all the entrires. I will start with this easy one just done.

![image](https://github.com/pzetairoi/TinyMRP/assets/86654415/4052fea3-949d-4012-bc5c-dae967028eea)

**Comment by pzetairoi** [comment]
Done and tested
