### ISSUE TITLE
SPACE BETWEEN BROWSE & UPLOAD EXCEL  WHEN COMPILING

### ISSUE THREAD

**Issue by NickMECS** [pzetairoi/TinyMRP#6]
![image](https://github.com/pzetairoi/TinyMRP/assets/167039369/4189c8d9-3c75-425f-bbd1-20a03547eaaa)

**Comment by pzetairoi** [comment]
Done

![image](https://github.com/pzetairoi/TinyMRP/assets/86654415/14a086ff-9075-4719-a18e-b3f44a618333)
