### ISSUE TITLE
PDF BINDER NO HEADING ON FRONT PAGE

### ISSUE THREAD

**Issue by NickMECS** [pzetairoi/TinyMRP#7]
Maybe even PDF Binder with date & time so as it can be seen what version

![image](https://github.com/pzetairoi/TinyMRP/assets/167039369/8a16c446-c0f3-4752-bf49-7ca1972716fc)

**Comment by pzetairoi** [comment]
The file name that is generated has a file stamp, for example:

xxx-Z-001621_REV_1-25_05_2024-15_24_17_660412.pdf

It was generated on 25/05/2024 at 15:24:17 and 666412 nanoseconds
