### ISSUE TITLE
DOCUMENT PACK HEADING

### ISSUE THREAD

**Issue by NickMECS** [pzetairoi/TinyMRP#8]
Is this at the moment
![image](https://github.com/pzetairoi/TinyMRP/assets/167039369/7f2583c2-e6d5-4314-a5e2-0b898596d274)

Old Tiny had 
![image](https://github.com/pzetairoi/TinyMRP/assets/167039369/58b1dd20-3132-4181-ac50-4c083b0689eb)

**Comment by pzetairoi** [comment]
Done:
![image](https://github.com/pzetairoi/TinyMRP/assets/86654415/5974d11c-3ea9-4073-8121-79e6f02c2509)
