### ISSUE TITLE
LOGO'S

### ISSUE THREAD

**Issue by NickMECS** [pzetairoi/TinyMRP#9]
It would be good to have MECS Logo top left hand corner of index & visual index page
![image](https://github.com/pzetairoi/TinyMRP/assets/167039369/52951c74-d2bf-4c4b-ad69-1431fd730f29)
& TINY MRP LOGO 
Middle bottom of each page

**Comment by pzetairoi** [comment]
Done 

![image](https://github.com/pzetairoi/TinyMRP/assets/86654415/fa7d43d5-6523-4b82-8353-50dfb2d347cb)
